global proc fix_deleteShit ()
{

	print ("found "+size (`ls -type "script"`)+" animationScriptNodes \n");
	delete (`ls -type "script"`);
	print ("found "+size (`ls -type "polyCylinder"`)+" polyCylinders \n");
	delete (`ls -type "polyCylinder"`);
	print ("found "+size (`ls -type "brush"`)+" brushes \n");
	delete (`ls -type "brush"`);
	print ("found "+size (`ls -type "partition" "*mtorPartition*"`)+" MTOR Partition \n");
	delete (`ls -type "partition" "*mtorPartition*"`);
}
